apiVersion: v1
kind: Service
metadata:
  name: echo
  labels:
    app.kubernetes.io/name: "echo"
    app.kubernetes.io/version: "35"
spec:
  type: LoadBalancer
  selector:
    app: echo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
